name: dk_manager
description: "Mobile case inventory management application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  iconsax: ^0.0.8
  fl_chart: ^0.66.0
  image_picker: ^1.0.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  dotted_border: ^2.1.0
  intl: ^0.19.0
  amazon_cognito_identity_dart_2: ^3.6.0
  http: ^1.2.0
  path: ^1.8.3
  uuid: ^4.3.3
  crypto: ^3.0.3
  device_info_plus: ^9.1.2
  minio: ^3.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_image_compress: ^2.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo.png
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
