// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYCVYcYfe5udrOmfIVBf50VloScDvyy1U',
    appId: '1:90163557637:android:391a7c03d2619ffe06b36c',
    messagingSenderId: '90163557637',
    projectId: 'inventory-managment-b6625',
    storageBucket: 'inventory-managment-b6625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6rInrtBn1J96cDLSPaDSSo_WdpHVDing',
    appId: '1:90163557637:ios:6f483e5d0386d90e06b36c',
    messagingSenderId: '90163557637',
    projectId: 'inventory-managment-b6625',
    storageBucket: 'inventory-managment-b6625.firebasestorage.app',
    androidClientId: '90163557637-439gi9ek1r1uqaralb97k9jbgd0mqh2p.apps.googleusercontent.com',
    iosClientId: '90163557637-9d2nej72clv80m53q2ovj7gaokj2rp2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.dkManager',
  );
}
